const TILE_SIZE = 20
const COLS = 28
const ROWS = 31
const CANVAS_WIDTH = COLS * TILE_SIZE
const CANVAS_HEIGHT = ROWS * TILE_SIZE

const DIR = { NONE: 0, UP: 1, DOWN: 2, LEFT: 3, RIGHT: 4 }
const MODE = { TITLE: 0, READY: 1, PLAYING: 2, DYING: 3, GAME_OVER: 4, WIN: 5 }

const TILE = { EMPTY: 0, WALL: 1, PELLET: 2, POWER_PELLET: 3, GHOST_HOUSE: 4, GHOST_DOOR: 5 }

const PACMAN_SPEED = 2
const GHOST_SPEED = 2
const GHOST_FRIGHTENED_SPEED = 1.0
const GHOST_EATEN_SPEED = 4.0
const GHOST_HOUSE_SPEED = 0.5

const SCATTER_DURATION = 7
const CHASE_DURATION = 20
const FRIGHTENED_DURATION = 6

const COLORS = {
    WALL: '#2121DE',
    PELLET: '#FFB8AE',
    POWER_PELLET: '#FFB8AE',
    PACMAN: '#FFFF00',
    BLINKY: '#FF0000',
    PINKY: '#FFB8FF',
    INKY: '#00FFFF',
    CLYDE: '#FFB852',
    FRIGHTENED: '#2121FF',
    FRIGHTENED_FLASH: '#FFFFFF',
    BACKGROUND: '#000000',
    TEXT: '#FFFF00',
    SCORE: '#FFFFFF',
    GHOST_EYES: '#FFFFFF'
}
